# Generated by Django 2.2.6 on 2021-12-10 11:02

import jsonfield.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="CourseTable",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "course_name",
                    models.CharField(
                        blank=True, max_length=90, null=True, verbose_name="课程名称"
                    ),
                ),
                (
                    "course_introduction",
                    models.TextField(blank=True, verbose_name="课程简介"),
                ),
                ("teacher", jsonfield.fields.JSONField(verbose_name="教师姓名")),
                ("create_people", jsonfield.fields.JSONField(verbose_name="创建人")),
                (
                    "manage_student",
                    jsonfield.fields.JSONField(null=True, verbose_name="学生管理员"),
                ),
            ],
        ),
        migrations.CreateModel(
            name="CourseConnect",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "course_id",
                    models.ForeignKey(on_delete="课程id", to="course.CourseTable"),
                ),
            ],
        ),
    ]
