# Generated by Django 2.2.24 on 2021-12-17 03:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course_name', models.CharField(max_length=90, verbose_name='课程名称')),
                ('course_introduction', models.TextField(blank=True, null=True, verbose_name='课程简介')),
                ('teacher', models.CharField(max_length=90, verbose_name='教师姓名')),
                ('create_people', models.CharField(max_length=90, verbose_name='创建人')),
                ('manage_student', models.TextField(blank=True, null=True, verbose_name='学生管理员')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='课程创建时间')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='课程更新时间')),
            ],
            options={
                'db_table': 'course',
                'ordering': ['-update_time'],
            },
        ),
        migrations.CreateModel(
            name='Member',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=50, unique=True, verbose_name='saas用户名')),
                ('openid', models.CharField(blank=True, max_length=50, null=True, verbose_name='wechat唯一标识')),
                ('class_number', models.CharField(blank=True, max_length=30, null=True, unique=True, verbose_name='学号/工号')),
                ('name', models.CharField(blank=True, max_length=30, null=True, verbose_name='姓名')),
                ('professional_class', models.CharField(blank=True, max_length=30, null=True, verbose_name='专业班级')),
                ('gender', models.CharField(blank=True, choices=[('MAN', '男'), ('WOMAN', '女')], max_length=20, null=True)),
                ('identity', models.CharField(choices=[('TEACHER', '老师'), ('STUDENT', '学生'), ('NOT_CERTIFIED', '未认证')], default='NOT_CERTIFIED', max_length=20)),
                ('phone_number', models.CharField(blank=True, max_length=30, null=True, verbose_name='手机号')),
                ('email_number', models.EmailField(blank=True, max_length=50, null=True, verbose_name='邮箱')),
                ('qq_number', models.CharField(blank=True, max_length=30, null=True, verbose_name='QQ号')),
                ('wechat_number', models.CharField(blank=True, max_length=50, null=True, verbose_name='微信号')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='课程创建时间')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='课程更新时间')),
            ],
            options={
                'db_table': 'member',
                'ordering': ['class_number'],
            },
        ),
        migrations.CreateModel(
            name='UserCourseContact',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.IntegerField(verbose_name='用户id')),
                ('course_id', models.IntegerField(verbose_name='课程id')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='成员加入课程时间')),
            ],
            options={
                'db_table': 'user_course_contact',
                'ordering': ['-create_time'],
            },
        ),
    ]
