# Generated by Django 2.2.24 on 2022-01-09 03:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='college',
            field=models.CharField(blank=True, max_length=40, null=True, verbose_name='学院'),
        ),
    ]
