# Generated by Django 2.2.6 on 2021-12-10 12:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("course", "0002_auto_20211210_2004"),
    ]

    operations = [
        migrations.DeleteModel(
            name="UserCourseContact",
        ),
    ]
