# Generated by Django 2.2.24 on 2022-01-26 12:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0003_chapter_customtype_paper_paperquestioncontact_question_studentanswer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='openid',
            field=models.CharField(blank=True, max_length=50, null=True, unique=True, verbose_name='wechat唯一标识'),
        ),
        migrations.AlterField(
            model_name='member',
            name='username',
            field=models.CharField(blank=True, max_length=50, null=True, unique=True, verbose_name='saas用户名'),
        ),
    ]
