# Generated by Django 2.2.6 on 2021-12-10 12:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("course", "0003_delete_usercoursecontact"),
    ]

    operations = [
        migrations.CreateModel(
            name="UserCourseContact",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("user_id", models.IntegerField(verbose_name="用户id")),
                ("course_id", models.IntegerField(verbose_name="课程id")),
            ],
        ),
    ]
