# Generated by Django 2.2.6 on 2022-02-11 07:12

from django.db import migrations, models
import django_mysql.models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0004_auto_20220126_2058'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='paperquestioncontact',
            name='custom_type_id',
        ),
        migrations.AddField(
            model_name='paper',
            name='question_order',
            field=django_mysql.models.JSONField(blank=True, default=None, null=True, verbose_name='存储题目顺序的Json'),
        ),
        migrations.AlterField(
            model_name='paper',
            name='status',
            field=models.CharField(choices=[('DRAFT', '草稿'), ('RELEASE', '已发布'), ('MARKED', '已批阅')], max_length=10, verbose_name='卷子状态'),
        ),
        migrations.AlterField(
            model_name='paperquestioncontact',
            name='types',
            field=models.CharField(choices=[('SINGLE', '单选题'), ('MULTIPLE', '多选题'), ('COMPLETION', '填空题'), ('JUDGE', '判断题'), ('SHORT_ANSWER', '简答题')], max_length=20, verbose_name='题目类型'),
        ),
    ]
