# Generated by Django 2.2.6 on 2021-12-10 12:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("course", "0004_usercoursecontact"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Course",
        ),
    ]
