# Generated by Django 2.2.6 on 2022-02-18 07:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0005_auto_20220211_1512'),
    ]

    operations = [
        migrations.CreateModel(
            name='StudentPaperContact',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course_id', models.IntegerField(verbose_name='课程id')),
                ('paper_id', models.IntegerField(verbose_name='卷子id')),
                ('student_id', models.TextField(verbose_name='学生id')),
                ('status', models.CharField(choices=[('NOT_ANSWER', '未答题'), ('SAVED', '已保存'), ('SUBMITTED', '已提交')], max_length=10, verbose_name='状态')),
                ('score', models.FloatField(blank=True, null=True, verbose_name='总分')),
            ],
        ),
        migrations.AlterField(
            model_name='studentanswer',
            name='answer',
            field=models.TextField(blank=True, null=True, verbose_name='学生的作答'),
        ),
    ]
