# Generated by Django 2.2.6 on 2021-12-10 13:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("course", "0006_course"),
    ]

    operations = [
        migrations.AlterField(
            model_name="course",
            name="course_introduction",
            field=models.TextField(blank=True, null=True, verbose_name="课程简介"),
        ),
        migrations.AlterField(
            model_name="course",
            name="course_name",
            field=models.CharField(max_length=90, verbose_name="课程名称"),
        ),
    ]
