# Generated by Django 2.2.6 on 2022-02-23 11:02

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0006_auto_20220218_1528'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentpapercontact',
            name='cumulative_time',
            field=models.DurationField(default=datetime.timedelta(0)),
        ),
    ]
