# Generated by Django 2.2.6 on 2021-12-11 11:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0007_auto_20211210_2129'),
    ]

    operations = [
        migrations.CreateModel(
            name='Member',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=50, verbose_name='saas用户名')),
                ('openid', models.CharField(blank=True, max_length=50, null=True, verbose_name='wechat唯一标识')),
                ('class_number', models.CharField(blank=True, max_length=30, null=True, verbose_name='学号/工号')),
                ('name', models.CharField(max_length=30, verbose_name='姓名')),
                ('professional_class', models.CharField(blank=True, max_length=30, null=True, verbose_name='专业班级')),
                ('gender', models.CharField(choices=[('MAN', '男'), ('WOMAN', '女')], max_length=20)),
                ('identity', models.CharField(choices=[('TEACHER', '老师'), ('STUDENT', '学生'), ('NOT_CERTIFIED', '未认证')], default='NOT_CERTIFIED', max_length=20)),
                ('phone_number', models.CharField(blank=True, max_length=30, null=True, verbose_name='手机号')),
                ('email_number', models.EmailField(blank=True, max_length=50, null=True, verbose_name='邮箱')),
                ('qq_number', models.CharField(blank=True, max_length=30, null=True, verbose_name='QQ号')),
                ('wechat_number', models.CharField(blank=True, max_length=50, null=True, verbose_name='微信号')),
            ],
        ),
    ]
