# Generated by Django 2.2.6 on 2022-03-04 10:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0008_auto_20220225_2025'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentpapercontact',
            name='status',
            field=models.CharField(choices=[('NOT_ANSWER', '未答题'), ('SAVED', '已保存'), ('SUBMITTED', '已提交'), ('MARKED', '已批改')], max_length=10, verbose_name='状态'),
        ),
    ]
