# Generated by Django 3.2.4 on 2022-04-10 07:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("userManager", "0002_usertag_tag_comment"),
    ]

    operations = [
        migrations.AlterField(
            model_name="usertag",
            name="tag_comment",
            field=models.CharField(max_length=30, null=True, verbose_name="备注"),
        ),
    ]
