# Generated by Django 3.2.4 on 2022-04-29 14:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("question", "0002_rename_user_id_questiontagcontact_question_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="questiontagcontact",
            name="question_id",
            field=models.BigIntegerField(verbose_name="问题id"),
        ),
    ]
