# Generated by Django 3.2.4 on 2022-04-11 10:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("user_manager", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelTable(
            name="usertagcontact",
            table=None,
        ),
    ]
