# Generated by Django 3.2.4 on 2022-04-10 07:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("user_manager", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="usertag",
            name="tag_comment",
            field=models.CharField(default="", max_length=30, verbose_name="备注"),
            preserve_default=False,
        ),
    ]
