# Generated by Django 3.2.4 on 2022-04-27 14:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("user_manager", "0007_alter_usertag_tag_value"),
    ]

    operations = [
        migrations.AddField(
            model_name="usertag",
            name="created_by",
            field=models.CharField(max_length=30, null=True, verbose_name="创建者"),
        ),
        migrations.AlterField(
            model_name="usertag",
            name="tag_value",
            field=models.CharField(max_length=20, verbose_name="标签值"),
        ),
    ]
