# Generated by Django 3.2.4 on 2022-05-20 11:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("user_manager", "0008_auto_20220427_2244"),
    ]

    operations = [
        migrations.AlterField(
            model_name="usertag",
            name="tag_color",
            field=models.CharField(max_length=6, verbose_name="标签颜色"),
        ),
    ]
