# Generated by Django 3.2.4 on 2022-04-08 15:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("project", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="project",
            name="name",
            field=models.CharField(max_length=90, unique=True, verbose_name="项目名称"),
        ),
    ]
