# Generated by Django 3.2.4 on 2022-04-09 15:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("project", "0002_alter_project_name"),
    ]

    operations = [
        migrations.AlterModelTable(
            name="project",
            table=None,
        ),
    ]
