# Generated by Django 3.2.4 on 2022-04-14 14:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("project", "0003_alter_project_table"),
    ]

    operations = [
        migrations.AddField(
            model_name="project",
            name="updater",
            field=models.CharField(
                blank=True, max_length=90, null=True, verbose_name="更新人"
            ),
        ),
        migrations.AlterField(
            model_name="project",
            name="creator",
            field=models.CharField(
                blank=True, max_length=90, null=True, verbose_name="创建人"
            ),
        ),
    ]
