# Generated by Django 3.2.4 on 2022-04-14 08:29

import datetime
import re

import django.core.validators
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="ProjectTask",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("project_id", models.BigIntegerField(verbose_name="任务所属项目id")),
                (
                    "types",
                    models.CharField(
                        choices=[("DAILY", "日常任务"), ("ASSESSMENT", "考核任务")],
                        max_length=10,
                        verbose_name="任务类型",
                    ),
                ),
                ("title", models.CharField(max_length=255, verbose_name="任务名称")),
                (
                    "question_order",
                    models.CharField(
                        blank=True,
                        default="",
                        max_length=200,
                        null=True,
                        validators=[
                            django.core.validators.RegexValidator(
                                re.compile("^\\d+(?:\\,\\d+)*\\Z"),
                                code="invalid",
                                message="Enter only digits separated by commas.",
                            )
                        ],
                        verbose_name="存储题目顺序",
                    ),
                ),
                (
                    "create_time",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
                (
                    "start_time",
                    models.DateTimeField(blank=True, null=True, verbose_name="开始时间"),
                ),
                (
                    "end_time",
                    models.DateTimeField(blank=True, null=True, verbose_name="截止时间"),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("DRAFT", "草稿"),
                            ("RELEASE", "已发布"),
                            ("MARKED", "已批阅"),
                        ],
                        max_length=10,
                        verbose_name="任务状态",
                    ),
                ),
                ("judge_teachers", models.JSONField(verbose_name="评委老师id及其权重")),
                ("created_id", models.BigIntegerField(verbose_name="创建者id")),
                ("updated_id", models.BigIntegerField(verbose_name="更新者id")),
                (
                    "time_created",
                    models.DateTimeField(
                        default=django.utils.timezone.now, verbose_name="创建时间"
                    ),
                ),
                (
                    "time_updated",
                    models.DateTimeField(auto_now=True, verbose_name="修改时间"),
                ),
                (
                    "students_visible",
                    models.BooleanField(default=False, verbose_name="参与任务的学生是否匿名"),
                ),
                (
                    "students_task_id",
                    models.CharField(
                        blank=True,
                        default="",
                        max_length=200,
                        null=True,
                        validators=[
                            django.core.validators.RegexValidator(
                                re.compile("^\\d+(?:\\,\\d+)*\\Z"),
                                code="invalid",
                                message="Enter only digits separated by commas.",
                            )
                        ],
                        verbose_name="学生任务信息id",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="StudentProjectTaskInfo",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("student_id", models.BigIntegerField(verbose_name="学生id")),
                ("project_id", models.BigIntegerField(verbose_name="项目id")),
                ("project_task_id", models.BigIntegerField(verbose_name="任务id")),
                ("stu_answers", models.JSONField(verbose_name="学生提交答案列表")),
                ("individual_score", models.JSONField(verbose_name="学生题目单项得分")),
                (
                    "total_score",
                    models.FloatField(
                        blank=True, default=0, null=True, verbose_name="学生总体得分"
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("NOT_ANSWER", "未答题"),
                            ("SAVED", "已保存"),
                            ("SUBMITTED", "已提交"),
                            ("MARKED", "已批改"),
                            ("CANCEL", "已撤销"),
                        ],
                        max_length=10,
                        verbose_name="学生完成任务状态",
                    ),
                ),
                (
                    "cumulative_time",
                    models.DurationField(
                        default=datetime.timedelta(0), verbose_name="任务累计时间"
                    ),
                ),
                ("created_id", models.BigIntegerField(verbose_name="创建者id")),
                ("updated_id", models.BigIntegerField(verbose_name="更新者id")),
                (
                    "time_created",
                    models.DateTimeField(
                        default=django.utils.timezone.now, verbose_name="创建时间"
                    ),
                ),
                (
                    "time_updated",
                    models.DateTimeField(auto_now=True, verbose_name="修改时间"),
                ),
            ],
        ),
    ]
