# Generated by Django 3.2.4 on 2022-04-26 12:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("project_task", "0002_auto_20220425_2058"),
    ]

    operations = [
        migrations.RenameField(
            model_name="projecttask",
            old_name="judge_teachers_weight",
            new_name="judge_teachers_info",
        ),
    ]
