# Generated by Django 3.2.4 on 2022-04-27 08:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        (
            "project_task",
            "0003_rename_judge_teachers_weight_projecttask_judge_teachers_info",
        ),
    ]

    operations = [
        migrations.RenameField(
            model_name="studentprojecttaskinfo",
            old_name="updator_id",
            new_name="updater_id",
        ),
    ]
