# Generated by Django 3.2.4 on 2022-04-29 02:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("project_task", "0004_rename_updator_id_studentprojecttaskinfo_updater_id"),
    ]

    operations = [
        migrations.AddField(
            model_name="studentprojecttaskinfo",
            name="creator",
            field=models.TextField(default=12, verbose_name="创建者姓名"),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="studentprojecttaskinfo",
            name="updater",
            field=models.TextField(default=12, verbose_name="更新者姓名"),
            preserve_default=False,
        ),
    ]
